# Created with Sundry-Locale
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.28.0.schema.json

PackageIdentifier: DuckStudio.Sundry
PackageVersion: 1.10.0
PackageLocale: en-US
Publisher: DuckStudio
PublisherUrl: https://duckduckstudio.github.io/yazicbs.github.io/
PublisherSupportUrl: https://github.com/DuckDuckStudio/Sundry/issues
Author: 鸭鸭「カモ」
PackageName: Sundry
PackageUrl: https://github.com/DuckDuckStudio/Sundry/
License: GNU Affero General Public License v3.0
LicenseUrl: https://github.com/DuckDuckStudio/Sundry/blob/main/LICENSE
Copyright: Copyright (c) 鸭鸭「カモ」
CopyrightUrl: https://github.com/DuckDuckStudio/Sundry/blob/main/LICENSE
ShortDescription: >
  Sundry is a tool related to WinGet that assists you in more conveniently
  removing manifests, modifying manifests, and analyzing validation errors, and more.
Tags:
  - Manifest
  - Manifests
  - package-remove
  - WinGet
  - winget-pkgs
ReleaseNotesUrl: https://github.com/DuckDuckStudio/Sundry/releases/tag/1.10.0
Documentations:
  - DocumentLabel: Quick start
    DocumentUrl: https://github.com/DuckDuckStudio/Sundry/blob/main/README.md#使用说明
  - DocumentLabel: Detailed description of commands
    DocumentUrl: https://github.com/DuckDuckStudio/Sundry/blob/main/README.md#可用命令
  - DocumentLabel: Configuration File (config.json) Document
    DocumentUrl: https://github.com/DuckDuckStudio/Sundry/blob/main/docs/config/README.md
ReleaseNotes: |-
  ## 新功能
  - feat(ignore): 在 Ubuntu 上支持 list 操作 (#330) by @DuckDuckStudio in #396
  - feat(config): 当用户试图更新配置项 $schema、version 的值时，警告用户 by @DuckDuckStudio in #423
  - feat: 添加清单版本 1.28.0 (#428) by @DuckDuckStudio in #429
  - feat(func/config): 读取 debug 配置时一律启用静默模式 by @DuckDuckStudio in #424

  ## 修复
  - fix(func/constant/paths): 依照是否已打包来区分 Sundry 所在文件夹的获取方式 by @DuckDuckStudio in #411
  - fix: 为请求添加超时时间（30秒） by @DuckDuckStudio in #436

  ## 重构
  - refactor: 移除不可能匹配的别名 Version (#389) by @DuckDuckStudio in #391
  - refactor: 简化 import xxx.a as a 为 from xxx import a by @DuckDuckStudio in #409
  - refactor(func/config): 去掉无意义的 while True by @DuckDuckStudio in #426
  - refactor(config): 将 func/config 的 获取当前配置版本 函数中的检查并入 验证配置 函数，并修改调用处直接使用 读取配置 函数 by @DuckDuckStudio in #427
  - refactor: 避免隐藏外部作用域定义 by @DuckDuckStudio in #437

  ## 依赖更新
  - chore(deps): 将 ajaw 的版本要求从 ~=1.0.1 更新为 ~=1.1.2 by @dependabot[bot] in #397 & #405 & #418
  - chore(deps): 将 catfood 从 2.2.2 更新至 2.3.0 by @dependabot[bot] & @DuckDuckStudio in #401

  ### CI/CD
  - ci(build): 使用 DuckDuckStudio/setup-innosetup7 安装 Inno Setup 7 by @DuckDuckStudio in #392
  - chore(deps): 将 astral-sh/setup-uv 从 10.0.1 更新至 10.2.0 by @dependabot[bot] in #399 & #406
  - chore(deps-dev): 将 pyinstaller 从 6.22.2 更新至 6.22.3 by @dependabot[bot] in #402

  ### Dev
  - chore(dev-deps): 调整开发依赖的定义 by @DuckDuckStudio in #388
    - chore(dev-deps): 添加测试依赖
      - pytest~=9.1 (在 #393 中更新)
      - pytest-cov~=7.1
    - chore: 将开发依赖定义在依赖组下而不是可选依赖
  - chore(deps-dev): 将 ty 的版本要求从 ~=0.0.77 更新为 ~=0.0.84 by @dependabot[bot] in #394 & #398 & #400 & #403 & #404 & #407

  ---

  完整修改记录: https://github.com/DuckDuckStudio/Sundry/compare/1.9.3...1.10.0
ManifestType: locale
ManifestVersion: 1.28.0
