# Created with Sundry-Locale
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: DuckStudio.Sundry
PackageVersion: 1.10.0
UpgradeBehavior: install
Commands:
  - sundry
Dependencies:
  PackageDependencies:
    - PackageIdentifier: Git.Git
    - PackageIdentifier: GitHub.cli
ReleaseDate: 2026-10-02 # Asia/Shanghai (UTC+8)
Installers:
  # Zip
  - Architecture: x64
    InstallerType: zip
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: sundry.exe
    InstallerUrl: https://github.com/DuckDuckStudio/Sundry/releases/download/1.10.0/Sundry.zip
    InstallerSha256: E5FDA34976AF03CCED2E1468A80C54B94B381156ADA32F21B9C26C714390268E
  - Architecture: arm64
    InstallerType: zip
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: sundry.exe
    InstallerUrl: https://github.com/DuckDuckStudio/Sundry/releases/download/1.10.0/Sundry.zip
    InstallerSha256: E5FDA34976AF03CCED2E1468A80C54B94B381156ADA32F21B9C26C714390268E

  # Inno
  - Architecture: x64
    InstallerType: inno
    Scope: machine
    ElevationRequirement: elevatesSelf
    InstallationMetadata:
      DefaultInstallLocation: '%ProgramFiles%\Sundry'
    InstallModes:
      - interactive
      - silent
      - silentWithProgress
    InstallerUrl: https://github.com/DuckDuckStudio/Sundry/releases/download/1.10.0/Sundry_Setup.exe
    InstallerSha256: D80ED118A3372F9E27790FFD54C481B01CB7296F115A263B3FAE3D78FC406180
  - Architecture: arm64
    InstallerType: inno
    Scope: machine
    ElevationRequirement: elevatesSelf
    InstallationMetadata:
      DefaultInstallLocation: '%ProgramFiles%\Sundry'
    InstallModes:
      - interactive
      - silent
      - silentWithProgress
    InstallerUrl: https://github.com/DuckDuckStudio/Sundry/releases/download/1.10.0/Sundry_Setup.exe
    InstallerSha256: D80ED118A3372F9E27790FFD54C481B01CB7296F115A263B3FAE3D78FC406180
ManifestType: installer
ManifestVersion: 1.28.0
