# Created with Sundry.
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: Denemo.Denemo
PackageVersion: "2.44"
PackageLocale: en-US
Publisher: Denemo
# PublisherUrl:
# PublisherSupportUrl:
# PrivacyUrl:
# Author:
PackageName: Denemo
# PackageUrl:
License: GPL-3.0-or-later
# LicenseUrl:
# Copyright:
# CopyrightUrl:
ShortDescription: Denemo is a scorewriter and music sequencer.
# Description:
# Moniker:
# Tags:
# ReleaseNotes:
# ReleaseNotesUrl:
# PurchaseUrl:
# InstallationNotes:
# Documentations:
ManifestType: defaultLocale
ManifestVersion: 1.10.0
